In [1]:
!pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting mlxtend
  Downloading mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: scipy>=1.16.3 in d:\anaconda\lib\site-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=2.3.5 in d:\anaconda\lib\site-packages (from mlxtend) (2.3.5)
Requirement already satisfied: pandas>=2.3.3 in d:\anaconda\lib\site-packages (from mlxtend) (2.3.3)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Downloading matplotlib-3.11.1-cp313-cp313-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: joblib>=1.5.2 in d:\anaconda\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in d:\anaconda\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in d:\anaconda\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.28.2 in d:\anaconda\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in d:\anaconda\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in d:\anaconda\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=9 in d:\anaconda\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in d:\anaconda\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in d:\anaconda\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\anaconda\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\anaconda\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in d:\anaconda\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in d:\anaconda\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in d:\anaconda\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)
Downloading mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 218.4 kB/s eta 0:00:04
   --------------- ------------------------ 0.5/1.4 MB 218.4 kB/s eta 0:00:04
   --------------- ------------------------ 0.5/1.4 MB 218.4 kB/s eta 0:00:04
   --------------- ------------------------ 0.5/1.4 MB 218.4 kB/s eta 0:00:04
   --------------- ------------------------ 0.5/1.4 MB 218.4 kB/s eta 0:00:04
   ----------------------- ---------------- 0.8/1.4 MB 227.8 kB/s eta 0:00:03
   ----------------------- ---------------- 0.8/1.4 MB 227.8 kB/s eta 0:00:03
   ----------------------- ---------------- 0.8/1.4 MB 227.8 kB/s eta 0:00:03
   ----------------------- ---------------- 0.8/1.4 MB 227.8 kB/s eta 0:00:03
   ----------------------- ---------------- 0.8/1.4 MB 227.8 kB/s eta 0:00:03
   ------------------------------ --------- 1.0/1.4 MB 249.0 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 249.0 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 249.0 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 249.0 kB/s eta 0:00:02
   -------------------------------------- - 1.3/1.4 MB 255.3 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 255.7 kB/s  0:00:07
Downloading matplotlib-3.11.1-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.3 MB 503.1 kB/s eta 0:00:18
   -- ------------------------------------- 0.5/9.3 MB 503.1 kB/s eta 0:00:18
   --- ------------------------------------ 0.8/9.3 MB 544.6 kB/s eta 0:00:16
   --- ------------------------------------ 0.8/9.3 MB 544.6 kB/s eta 0:00:16
   ---- ----------------------------------- 1.0/9.3 MB 551.8 kB/s eta 0:00:16
   ---- ----------------------------------- 1.0/9.3 MB 551.8 kB/s eta 0:00:16
   ---- ----------------------------------- 1.0/9.3 MB 551.8 kB/s eta 0:00:16
   ---- ----------------------------------- 1.0/9.3 MB 551.8 kB/s eta 0:00:16
   ----- ---------------------------------- 1.3/9.3 MB 477.7 kB/s eta 0:00:17
   ----- ---------------------------------- 1.3/9.3 MB 477.7 kB/s eta 0:00:17
   ----- ---------------------------------- 1.3/9.3 MB 477.7 kB/s eta 0:00:17
   ------ --------------------------------- 1.6/9.3 MB 466.6 kB/s eta 0:00:17
   ------ --------------------------------- 1.6/9.3 MB 466.6 kB/s eta 0:00:17
   ------ --------------------------------- 1.6/9.3 MB 466.6 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.3 MB 465.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.3 MB 465.2 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.3 MB 465.2 kB/s eta 0:00:17
   -------- ------------------------------- 2.1/9.3 MB 461.3 kB/s eta 0:00:16
   -------- ------------------------------- 2.1/9.3 MB 461.3 kB/s eta 0:00:16
   ---------- ----------------------------- 2.4/9.3 MB 476.6 kB/s eta 0:00:15
   ---------- ----------------------------- 2.4/9.3 MB 476.6 kB/s eta 0:00:15
   ---------- ----------------------------- 2.4/9.3 MB 476.6 kB/s eta 0:00:15
   ----------- ---------------------------- 2.6/9.3 MB 460.6 kB/s eta 0:00:15
   ----------- ---------------------------- 2.6/9.3 MB 460.6 kB/s eta 0:00:15
   ----------- ---------------------------- 2.6/9.3 MB 460.6 kB/s eta 0:00:15
   ------------ --------------------------- 2.9/9.3 MB 461.6 kB/s eta 0:00:14
   ------------ --------------------------- 2.9/9.3 MB 461.6 kB/s eta 0:00:14
   ------------ --------------------------- 2.9/9.3 MB 461.6 kB/s eta 0:00:14
   ------------- -------------------------- 3.1/9.3 MB 462.3 kB/s eta 0:00:14
   ------------- -------------------------- 3.1/9.3 MB 462.3 kB/s eta 0:00:14
   ------------- -------------------------- 3.1/9.3 MB 462.3 kB/s eta 0:00:14
   ------------- -------------------------- 3.1/9.3 MB 462.3 kB/s eta 0:00:14
   -------------- ------------------------- 3.4/9.3 MB 447.9 kB/s eta 0:00:14
   -------------- ------------------------- 3.4/9.3 MB 447.9 kB/s eta 0:00:14
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   --------------- ------------------------ 3.7/9.3 MB 452.9 kB/s eta 0:00:13
   ---------------- ----------------------- 3.9/9.3 MB 386.6 kB/s eta 0:00:14
   ---------------- ----------------------- 3.9/9.3 MB 386.6 kB/s eta 0:00:14
   ----------------- ---------------------- 4.2/9.3 MB 394.9 kB/s eta 0:00:14
   ------------------- -------------------- 4.5/9.3 MB 409.1 kB/s eta 0:00:12
   -------------------- ------------------- 4.7/9.3 MB 427.4 kB/s eta 0:00:11
   -------------------- ------------------- 4.7/9.3 MB 427.4 kB/s eta 0:00:11
   --------------------- ------------------ 5.0/9.3 MB 436.4 kB/s eta 0:00:10
   --------------------- ------------------ 5.0/9.3 MB 436.4 kB/s eta 0:00:10
   --------------------- ------------------ 5.0/9.3 MB 436.4 kB/s eta 0:00:10
   ---------------------- ----------------- 5.2/9.3 MB 436.7 kB/s eta 0:00:10
   ---------------------- ----------------- 5.2/9.3 MB 436.7 kB/s eta 0:00:10
   ---------------------- ----------------- 5.2/9.3 MB 436.7 kB/s eta 0:00:10
   ---------------------- ----------------- 5.2/9.3 MB 436.7 kB/s eta 0:00:10
   ---------------------- ----------------- 5.2/9.3 MB 436.7 kB/s eta 0:00:10
   ---------------------- ----------------- 5.2/9.3 MB 436.7 kB/s eta 0:00:10
   ---------------------- ----------------- 5.2/9.3 MB 436.7 kB/s eta 0:00:10
   ---------------------- ----------------- 5.2/9.3 MB 436.7 kB/s eta 0:00:10
   ----------------------- ---------------- 5.5/9.3 MB 399.4 kB/s eta 0:00:10
   ----------------------- ---------------- 5.5/9.3 MB 399.4 kB/s eta 0:00:10
   ----------------------- ---------------- 5.5/9.3 MB 399.4 kB/s eta 0:00:10
   ----------------------- ---------------- 5.5/9.3 MB 399.4 kB/s eta 0:00:10
   ----------------------- ---------------- 5.5/9.3 MB 399.4 kB/s eta 0:00:10
   ----------------------- ---------------- 5.5/9.3 MB 399.4 kB/s eta 0:00:10
   ------------------------ --------------- 5.8/9.3 MB 388.7 kB/s eta 0:00:10
   ------------------------- -------------- 6.0/9.3 MB 396.3 kB/s eta 0:00:09
   -------------------------- ------------- 6.3/9.3 MB 413.5 kB/s eta 0:00:08
   -------------------------- ------------- 6.3/9.3 MB 413.5 kB/s eta 0:00:08
   -------------------------- ------------- 6.3/9.3 MB 413.5 kB/s eta 0:00:08
   ---------------------------- ----------- 6.6/9.3 MB 412.0 kB/s eta 0:00:07
   ---------------------------- ----------- 6.6/9.3 MB 412.0 kB/s eta 0:00:07
   ---------------------------- ----------- 6.6/9.3 MB 412.0 kB/s eta 0:00:07
   ----------------------------- ---------- 6.8/9.3 MB 412.9 kB/s eta 0:00:07
   ----------------------------- ---------- 6.8/9.3 MB 412.9 kB/s eta 0:00:07
   ----------------------------- ---------- 6.8/9.3 MB 412.9 kB/s eta 0:00:07
   ------------------------------ --------- 7.1/9.3 MB 414.3 kB/s eta 0:00:06
   ------------------------------ --------- 7.1/9.3 MB 414.3 kB/s eta 0:00:06
   ------------------------------ --------- 7.1/9.3 MB 414.3 kB/s eta 0:00:06
   ------------------------------ --------- 7.1/9.3 MB 414.3 kB/s eta 0:00:06
   ------------------------------- -------- 7.3/9.3 MB 410.3 kB/s eta 0:00:05
   ------------------------------- -------- 7.3/9.3 MB 410.3 kB/s eta 0:00:05
   -------------------------------- ------- 7.6/9.3 MB 414.9 kB/s eta 0:00:05
   -------------------------------- ------- 7.6/9.3 MB 414.9 kB/s eta 0:00:05
   --------------------------------- ------ 7.9/9.3 MB 416.8 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.3 MB 416.8 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.3 MB 416.8 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.3 MB 416.8 kB/s eta 0:00:04
   --------------------------------- ------ 7.9/9.3 MB 416.8 kB/s eta 0:00:04
   ---------------------------------- ----- 8.1/9.3 MB 408.5 kB/s eta 0:00:03
   ---------------------------------- ----- 8.1/9.3 MB 408.5 kB/s eta 0:00:03
   ---------------------------------- ----- 8.1/9.3 MB 408.5 kB/s eta 0:00:03
   ---------------------------------- ----- 8.1/9.3 MB 408.5 kB/s eta 0:00:03
   ---------------------------------- ----- 8.1/9.3 MB 408.5 kB/s eta 0:00:03
   ----------------------------------- ---- 8.4/9.3 MB 403.2 kB/s eta 0:00:03
   ----------------------------------- ---- 8.4/9.3 MB 403.2 kB/s eta 0:00:03
   ----------------------------------- ---- 8.4/9.3 MB 403.2 kB/s eta 0:00:03
   ------------------------------------- -- 8.7/9.3 MB 401.1 kB/s eta 0:00:02
   ------------------------------------- -- 8.7/9.3 MB 401.1 kB/s eta 0:00:02
   -------------------------------------- - 8.9/9.3 MB 404.9 kB/s eta 0:00:02
   -------------------------------------- - 8.9/9.3 MB 404.9 kB/s eta 0:00:02
   -------------------------------------- - 8.9/9.3 MB 404.9 kB/s eta 0:00:02
   ---------------------------------------  9.2/9.3 MB 407.7 kB/s eta 0:00:01
   ---------------------------------------  9.2/9.3 MB 407.7 kB/s eta 0:00:01
   ---------------------------------------- 9.3/9.3 MB 408.2 kB/s  0:00:22
Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 442.8 kB/s eta 0:00:18
   -- ------------------------------------- 0.5/8.2 MB 442.8 kB/s eta 0:00:18
   -- ------------------------------------- 0.5/8.2 MB 442.8 kB/s eta 0:00:18
   --- ------------------------------------ 0.8/8.2 MB 419.7 kB/s eta 0:00:18
   --- ------------------------------------ 0.8/8.2 MB 419.7 kB/s eta 0:00:18
   --- ------------------------------------ 0.8/8.2 MB 419.7 kB/s eta 0:00:18
   ----- ---------------------------------- 1.0/8.2 MB 425.2 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/8.2 MB 425.2 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/8.2 MB 425.2 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/8.2 MB 425.2 kB/s eta 0:00:17
   ----- ---------------------------------- 1.0/8.2 MB 425.2 kB/s eta 0:00:17
   ------ --------------------------------- 1.3/8.2 MB 374.2 kB/s eta 0:00:19
   ------ --------------------------------- 1.3/8.2 MB 374.2 kB/s eta 0:00:19
   ------ --------------------------------- 1.3/8.2 MB 374.2 kB/s eta 0:00:19
   ------ --------------------------------- 1.3/8.2 MB 374.2 kB/s eta 0:00:19
   ------ --------------------------------- 1.3/8.2 MB 374.2 kB/s eta 0:00:19
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   ------- -------------------------------- 1.6/8.2 MB 341.7 kB/s eta 0:00:20
   -------- ------------------------------- 1.8/8.2 MB 249.3 kB/s eta 0:00:26
   -------- ------------------------------- 1.8/8.2 MB 249.3 kB/s eta 0:00:26
   -------- ------------------------------- 1.8/8.2 MB 249.3 kB/s eta 0:00:26
   ---------- ----------------------------- 2.1/8.2 MB 265.4 kB/s eta 0:00:23
   ------------ --------------------------- 2.6/8.2 MB 328.8 kB/s eta 0:00:17
   ------------ --------------------------- 2.6/8.2 MB 328.8 kB/s eta 0:00:17
   -------------- ------------------------- 2.9/8.2 MB 348.9 kB/s eta 0:00:16
   -------------- ------------------------- 2.9/8.2 MB 348.9 kB/s eta 0:00:16
   -------------- ------------------------- 2.9/8.2 MB 348.9 kB/s eta 0:00:16
   --------------- ------------------------ 3.1/8.2 MB 346.1 kB/s eta 0:00:15
   --------------- ------------------------ 3.1/8.2 MB 346.1 kB/s eta 0:00:15
   --------------- ------------------------ 3.1/8.2 MB 346.1 kB/s eta 0:00:15
   --------------- ------------------------ 3.1/8.2 MB 346.1 kB/s eta 0:00:15
   --------------- ------------------------ 3.1/8.2 MB 346.1 kB/s eta 0:00:15
   ---------------- ----------------------- 3.4/8.2 MB 337.3 kB/s eta 0:00:15
   ---------------- ----------------------- 3.4/8.2 MB 337.3 kB/s eta 0:00:15
   ---------------- ----------------------- 3.4/8.2 MB 337.3 kB/s eta 0:00:15
   ----------------- ---------------------- 3.7/8.2 MB 345.8 kB/s eta 0:00:14
   ----------------- ---------------------- 3.7/8.2 MB 345.8 kB/s eta 0:00:14
   ------------------- -------------------- 3.9/8.2 MB 356.1 kB/s eta 0:00:12
   ------------------- -------------------- 3.9/8.2 MB 356.1 kB/s eta 0:00:12
   -------------------- ------------------- 4.2/8.2 MB 367.4 kB/s eta 0:00:11
   -------------------- ------------------- 4.2/8.2 MB 367.4 kB/s eta 0:00:11
   -------------------- ------------------- 4.2/8.2 MB 367.4 kB/s eta 0:00:11
   -------------------- ------------------- 4.2/8.2 MB 367.4 kB/s eta 0:00:11
   --------------------- ------------------ 4.5/8.2 MB 367.6 kB/s eta 0:00:11
   --------------------- ------------------ 4.5/8.2 MB 367.6 kB/s eta 0:00:11
   --------------------- ------------------ 4.5/8.2 MB 367.6 kB/s eta 0:00:11
   ----------------------- ---------------- 4.7/8.2 MB 366.0 kB/s eta 0:00:10
   ----------------------- ---------------- 4.7/8.2 MB 366.0 kB/s eta 0:00:10
   ----------------------- ---------------- 4.7/8.2 MB 366.0 kB/s eta 0:00:10
   ------------------------ --------------- 5.0/8.2 MB 373.1 kB/s eta 0:00:09
   ------------------------ --------------- 5.0/8.2 MB 373.1 kB/s eta 0:00:09
   ------------------------- -------------- 5.2/8.2 MB 380.0 kB/s eta 0:00:08
   ------------------------- -------------- 5.2/8.2 MB 380.0 kB/s eta 0:00:08
   ------------------------- -------------- 5.2/8.2 MB 380.0 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.2 MB 380.5 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.2 MB 380.5 kB/s eta 0:00:08
   -------------------------- ------------- 5.5/8.2 MB 380.5 kB/s eta 0:00:08
   ---------------------------- ----------- 5.8/8.2 MB 385.5 kB/s eta 0:00:07
   ---------------------------- ----------- 5.8/8.2 MB 385.5 kB/s eta 0:00:07
   ----------------------------- ---------- 6.0/8.2 MB 391.9 kB/s eta 0:00:06
   ----------------------------- ---------- 6.0/8.2 MB 391.9 kB/s eta 0:00:06

# 1.Import Necessary Libraries

In [3]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

# 2. Import Dataset

In [4]:
online_retaile_data= pd.read_excel("Online Retail.xlsx")
online_retaile_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

# 3.Data Understanding

In [5]:
online_retaile_data.shape

(541909, 8)

In [6]:
online_retaile_data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
online_retaile_data.describe(include="all")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
count,541909.0,541909,540455,541909.000000,541909,541909.000000,406829.000000,541909
unique,25900.0,4070,4223,NaN,NaN,NaN,NaN,38
top,573585.0,85123A,WHITE HANGING HEART T-LIGHT HOLDER,NaN,NaN,NaN,NaN,United Kingdom
freq,1114.0,2313,2369,NaN,NaN,NaN,NaN,495478
mean,NaN,NaN,NaN,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570,NaN
min,NaN,NaN,NaN,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,NaN
25%,NaN,NaN,NaN,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,NaN
50%,NaN,NaN,NaN,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,NaN
75%,NaN,NaN,NaN,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,NaN
max,NaN,NaN,NaN,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,NaN
std,NaN,NaN,NaN,218.081158,NaN,96.759853,1713.600303,NaN

In [18]:
online_retaile_data.nunique()

InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64

In [14]:
online_retaile_data["Country"].nunique()

38

In [15]:
online_retaile_data["Country"].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Austria',
       'Israel', 'Finland', 'Bahrain', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

### I want to find out the total transactions happened in each country

In [19]:
online_retaile_data["Country"].value_counts()

Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64

## Let's build BEST ASSOCIATES for UK as it has more transactions

In [38]:
uk_data = online_retaile_data[online_retaile_data["Country"] == 'United Kingdom']
uk_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [39]:
uk_data.shape

(495478, 8)

In [40]:
uk_data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     133600
Country             0
dtype: int64

In [41]:
 1454/495478

0.002934539979575279

In [42]:
del uk_data["CustomerID"]

In [43]:
uk_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,United Kingdom

In [44]:
uk_data.dropna(inplace=True)

In [45]:
uk_data.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
Country        0
dtype: int64

In [49]:
uk_pivotted_data= pd.pivot_table(data = uk_data,values="Quantity",index="InvoiceNo",columns="Description",aggfunc=["sum"]).fillna(0)
uk_pivotted_data

              sum                                 \
Description 20713  4 PURPLE FLOCK DINNER CANDLES
InvoiceNo
536365        0.0                            0.0
536366        0.0                            0.0
536367        0.0                            0.0
536368        0.0                            0.0
536369        0.0                            0.0
...           ...                            ...
C581484       0.0                            0.0
C581490       0.0                            0.0
C581499       0.0                            0.0
C581568       0.0                            0.0
C581569       0.0                            0.0

                                                               \
Description  50'S CHRISTMAS GIFT BAG LARGE  DOLLY GIRL BEAKER
InvoiceNo
536365                                 0.0                0.0
536366                                 0.0                0.0
536367                                 0.0                0.0
536368                                 0.0                0.0
536369                                 0.0                0.0
...                                    ...                ...
C581484                                0.0                0.0
C581490                                0.0                0.0
C581499                                0.0                0.0
C581568                                0.0                0.0
C581569                                0.0                0.0

                                                                   \
Description  I LOVE LONDON MINI BACKPACK  NINE DRAWER OFFICE TIDY
InvoiceNo
536365                               0.0                      0.0
536366                               0.0                      0.0
536367                               0.0                      0.0
536368                               0.0                      0.0
536369                               0.0                      0.0
...                                  ...                      ...
C581484                              0.0                      0.0
C581490                              0.0                      0.0
C581499                              0.0                      0.0
C581568                              0.0                      0.0
C581569                              0.0                      0.0

                                                                  \
Description  OVAL WALL MIRROR DIAMANTE   RED SPOT GIFT BAG LARGE
InvoiceNo
536365                              0.0                      0.0
536366                              0.0                      0.0
536367                              0.0                      0.0
536368                              0.0                      0.0
536369                              0.0                      0.0
...                                 ...                      ...
C581484                             0.0                      0.0
C581490                             0.0                      0.0
C581499                             0.0                      0.0
C581568                             0.0                      0.0
C581569                             0.0                      0.0

                                                                      ...  \
Description  SET 2 TEA TOWELS I LOVE LONDON   SPACEBOY BABY GIFT SET  ...
InvoiceNo                                                             ...
536365                                   0.0                     0.0  ...
536366                                   0.0                     0.0  ...
536367                                   0.0                     0.0  ...
536368                                   0.0                     0.0  ...
536369                                   0.0                     0.0  ...
...                                      ...                     ...  ...
C581484                                  0.0                     0.0  ...
C581490                                  0.0                     0.0  ...
C581499                                  0.0                     0.0  ...
C581568                                  0.0                     0.0  ...
C581569                                  0.0                     0.0  ...

                                                                         \
Description wrongly coded 20713 wrongly coded 23343 wrongly coded-23343
InvoiceNo
536365                      0.0                 0.0                 0.0
536366                      0.0                 0.0                 0.0
536367                      0.0                 0.0                 0.0
536368                      0.0                 0.0                 0.0
536369                      0.0                 0.0                 0.0
...                         ...                 ...                 ...
C581484                     0.0                 0.0                 0.0
C581490                     0.0                 0.0                 0.0
C581499                     0.0                 0.0                 0.0
C581568                     0.0                 0.0                 0.0
C581569                     0.0                 0.0                 0.0

                                                                             \
Description wrongly marked wrongly marked 23343 wrongly marked carton 22804
InvoiceNo
536365                 0.0                  0.0                         0.0
536366                 0.0                  0.0                         0.0
536367                 0.0                  0.0                         0.0
536368                 0.0                  0.0                         0.0
536369                 0.0                  0.0                         0.0
...                    ...                  ...                         ...
C581484                0.0                  0.0                         0.0
C581490                0.0                  0.0                         0.0
C581499                0.0                  0.0                         0.0
C581568                0.0                  0.0                         0.0
C581569                0.0                  0.0                         0.0

                                                                       \
Description wrongly marked. 23343 in box wrongly sold (22719) barcode
InvoiceNo
536365                               0.0                          0.0
536366                               0.0                          0.0
536367                               0.0                          0.0
536368                               0.0                          0.0
536369                               0.0                          0.0
...                                  ...                          ...
C581484                              0.0                          0.0
C581490                              0.0                          0.0
C581499                              0.0                          0.0
C581568                              0.0                          0.0
C581569                              0.0                          0.0


Description wrongly sold as sets wrongly sold sets
InvoiceNo
536365                       0.0               0.0
536366                       0.0               0.0
536367                       0.0               0.0
536368                       0.0               0.0
536369                       0.0               0.0
...                          ...               ...
C581484                      0.0               0.0
C581490                      0.0               0.0
C581499                      0.0               0.0
C581568                      0.0               0.0
C581569                      0.0               0.0

[22040 rows x 4202 columns]

In [50]:
uk_pivotted_data_onehot= uk_pivotted_data.map(lambda x :0 if x==0 else 1)
uk_pivotted_data_onehot

              sum                                 \
Description 20713  4 PURPLE FLOCK DINNER CANDLES
InvoiceNo
536365          0                              0
536366          0                              0
536367          0                              0
536368          0                              0
536369          0                              0
...           ...                            ...
C581484         0                              0
C581490         0                              0
C581499         0                              0
C581568         0                              0
C581569         0                              0

                                                               \
Description  50'S CHRISTMAS GIFT BAG LARGE  DOLLY GIRL BEAKER
InvoiceNo
536365                                   0                  0
536366                                   0                  0
536367                                   0                  0
536368                                   0                  0
536369                                   0                  0
...                                    ...                ...
C581484                                  0                  0
C581490                                  0                  0
C581499                                  0                  0
C581568                                  0                  0
C581569                                  0                  0

                                                                   \
Description  I LOVE LONDON MINI BACKPACK  NINE DRAWER OFFICE TIDY
InvoiceNo
536365                                 0                        0
536366                                 0                        0
536367                                 0                        0
536368                                 0                        0
536369                                 0                        0
...                                  ...                      ...
C581484                                0                        0
C581490                                0                        0
C581499                                0                        0
C581568                                0                        0
C581569                                0                        0

                                                                  \
Description  OVAL WALL MIRROR DIAMANTE   RED SPOT GIFT BAG LARGE
InvoiceNo
536365                                0                        0
536366                                0                        0
536367                                0                        0
536368                                0                        0
536369                                0                        0
...                                 ...                      ...
C581484                               0                        0
C581490                               0                        0
C581499                               0                        0
C581568                               0                        0
C581569                               0                        0

                                                                      ...  \
Description  SET 2 TEA TOWELS I LOVE LONDON   SPACEBOY BABY GIFT SET  ...
InvoiceNo                                                             ...
536365                                     0                       0  ...
536366                                     0                       0  ...
536367                                     0                       0  ...
536368                                     0                       0  ...
536369                                     0                       0  ...
...                                      ...                     ...  ...
C581484                                    0                       0  ...
C581490                                    0                       0  ...
C581499                                    0                       0  ...
C581568                                    0                       0  ...
C581569                                    0                       0  ...

                                                                         \
Description wrongly coded 20713 wrongly coded 23343 wrongly coded-23343
InvoiceNo
536365                        0                   0                   0
536366                        0                   0                   0
536367                        0                   0                   0
536368                        0                   0                   0
536369                        0                   0                   0
...                         ...                 ...                 ...
C581484                       0                   0                   0
C581490                       0                   0                   0
C581499                       0                   0                   0
C581568                       0                   0                   0
C581569                       0                   0                   0

                                                                             \
Description wrongly marked wrongly marked 23343 wrongly marked carton 22804
InvoiceNo
536365                   0                    0                           0
536366                   0                    0                           0
536367                   0                    0                           0
536368                   0                    0                           0
536369                   0                    0                           0
...                    ...                  ...                         ...
C581484                  0                    0                           0
C581490                  0                    0                           0
C581499                  0                    0                           0
C581568                  0                    0                           0
C581569                  0                    0                           0

                                                                       \
Description wrongly marked. 23343 in box wrongly sold (22719) barcode
InvoiceNo
536365                                 0                            0
536366                                 0                            0
536367                                 0                            0
536368                                 0                            0
536369                                 0                            0
...                                  ...                          ...
C581484                                0                            0
C581490                                0                            0
C581499                                0                            0
C581568                                0                            0
C581569                                0                            0


Description wrongly sold as sets wrongly sold sets
InvoiceNo
536365                         0                 0
536366                         0                 0
536367                         0                 0
536368                         0                 0
536369                         0                 0
...                          ...               ...
C581484                        0                 0
C581490                        0                 0
C581499                        0                 0
C581568                        0                 0
C581569                        0                 0

[22040 rows x 4202 columns]

# 4.Data Mining

In [46]:
from mlxtend.frequent_patterns import apriori,association_rules

In [60]:
freq_iremsets = apriori(df=uk_pivotted_data_onehot,min_support=0.03,use_colnames=True)
freq_iremsets

     support                                           itemsets
0   0.038884                    ((sum, 6 RIBBONS RUSTIC CHARM))
1   0.034483               ((sum, 60 TEATIME FAIRY CAKE CASES))
2   0.040563                ((sum, ALARM CLOCK BAKELIKE GREEN))
3   0.030445                 ((sum, ALARM CLOCK BAKELIKE PINK))
4   0.043512                 ((sum, ALARM CLOCK BAKELIKE RED ))
..       ...                                                ...
88  0.049546         ((sum, WOODEN PICTURE FRAME WHITE FINISH))
89  0.031307                    ((sum, WOODLAND CHARLOTTE BAG))
90  0.032350  ((sum, ROSES REGENCY TEACUP AND SAUCER ), (sum...
91  0.035980  ((sum, JUMBO BAG PINK POLKADOT), (sum, JUMBO B...
92  0.032078  ((sum, JUMBO BAG RED RETROSPOT), (sum, JUMBO S...

[93 rows x 2 columns]

In [61]:
best_associates = association_rules(df=freq_iremsets,min_threshold=0.02)
best_associates

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,"((sum, ROSES REGENCY TEACUP AND SAUCER ))","((sum, GREEN REGENCY TEACUP AND SAUCER))",0.045508,0.044011,0.032350,0.710867,16.152080,1.0,0.030347,3.306404,0.982815,0.565873,0.697557,0.722959
1,"((sum, GREEN REGENCY TEACUP AND SAUCER))","((sum, ROSES REGENCY TEACUP AND SAUCER ))",0.044011,0.045508,0.032350,0.735052,16.152080,1.0,0.030347,3.602557,0.981275,0.565873,0.722419,0.722959
2,"((sum, JUMBO BAG PINK POLKADOT))","((sum, JUMBO BAG RED RETROSPOT))",0.053176,0.089746,0.035980,0.676621,7.539297,1.0,0.031208,2.814823,0.916075,0.336445,0.644738,0.538766
3,"((sum, JUMBO BAG RED RETROSPOT))","((sum, JUMBO BAG PINK POLKADOT))",0.089746,0.053176,0.035980,0.400910,7.539297,1.0,0.031208,1.580437,0.952879,0.336445,0.367264,0.538766
4,"((sum, JUMBO BAG RED RETROSPOT))","((sum, JUMBO STORAGE BAG SUKI))",0.089746,0.052042,0.032078,0.357432,6.868174,1.0,0.027408,1.475265,0.938640,0.292390,0.322156,0.486911
5,"((sum, JUMBO STORAGE BAG SUKI))","((sum, JUMBO BAG RED RETROSPOT))",0.052042,0.089746,0.032078,0.616391,6.868174,1.0,0.027408,2.372867,0.901306,0.292390,0.578569,0.486911

In [62]:
best_associates.to_csv("best_anticidents_consequents.csv")

OSError: [Errno 28] No space left on device

# THE END!!!