## 1.Import Necessarie Libraries

In [21]:
import pandas as pd 

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

from datetime import datetime

from sklearn.datasets import load_breast_cancer

## 2.Impoer Dataset

In [47]:
breast_cancer_data = load_breast_cancer()

In [49]:
print(breast_cancer_data.DESCR)

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - class:
            - WDBC-Malignant
            - WDBC-Benign

:Summary Statistics:

===================================== ====== ======
                                        Min    Max
===================================== ====== ======
radius (mean):                        6.981  28.11
texture (mean):                       9.71   39.28
perimeter (mean):                     43.79  188.5
area (mean):                          143.5  2501.0
smoothness (mean):                    0.053  0.163
compactness (mean):                   0.019  0.345
concavity (mean):                     0.0    0.427
concave points (mean):                0.0    0.201
symmetry (mean):                      0.106  0.304
fractal dimension (mean):             0.05   0.097
radius (standard error):              0.112  2.873
texture (standard error):             0.36   4.885
perimeter (standard error):           0.757  21.98
area (standard error):                6.802  542.2
smoothness (standard error):          0.002  0.031
compactness (standard error):         0.002  0.135
concavity (standard error):           0.0    0.396
concave points (standard error):      0.0    0.053
symmetry (standard error):            0.008  0.079
fractal dimension (standard error):   0.001  0.03
radius (worst):                       7.93   36.04
texture (worst):                      12.02  49.54
perimeter (worst):                    50.41  251.2
area (worst):                         185.2  4254.0
smoothness (worst):                   0.071  0.223
compactness (worst):                  0.027  1.058
concavity (worst):                    0.0    1.252
concave points (worst):               0.0    0.291
symmetry (worst):                     0.156  0.664
fractal dimension (worst):            0.055  0.208
===================================== ====== ======

:Missing Attribute Values: None

:Class Distribution: 212 - Malignant, 357 - Benign

:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian

:Donor: Nick Street

:Date: November, 1995

This is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.
https://goo.gl/U2Uwz2

Features are computed from a digitized image of a fine needle
aspirate (FNA) of a breast mass.  They describe
characteristics of the cell nuclei present in the image.

Separating plane described above was obtained using
Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree
Construction Via Linear Programming." Proceedings of the 4th
Midwest Artificial Intelligence and Cognitive Science Society,
pp. 97-101, 1992], a classification method which uses linear
programming to construct a decision tree.  Relevant features
were selected using an exhaustive search in the space of 1-4
features and 1-3 separating planes.

The actual linear program used to obtain the separating plane
in the 3-dimensional space is that described in:
[K. P. Bennett and O. L. Mangasarian: "Robust Linear
Programming Discrimination of Two Linearly Inseparable Sets",
Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server:

ftp ftp.cs.wisc.edu
cd math-prog/cpo-dataset/machine-learn/WDBC/

.. dropdown:: References

  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction
    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on
    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,
    San Jose, CA, 1993.
  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and
    prognosis via linear programming. Operations Research, 43(4), pages 570-577,
    July-August 1995.
  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques
    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)
    163-171.

In [4]:
breast_cancer_data_df = pd.DataFrame(breast_cancer_data.data,columns=breast_cancer_data.feature_names)
breast_cancer_data_df["target"] = breast_cancer_data.target
breast_cancer_data_df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

## 3.Understand data

In [5]:
breast_cancer_data_df.shape

(569, 31)

In [6]:
breast_cancer_data_df.isna().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [7]:
breast_cancer_data_df.dtypes

mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points       float64
worst symmetry             float64
worst fractal dimension    float64
target                       int64
dtype: object

## 4.Data Preprocessing

In [8]:
x = breast_cancer_data_df.drop("target",axis=1)
y = breast_cancer_data_df.target

In [20]:
std_scalar = StandardScaler()
scaled_x = pd.DataFrame(std_scalar.fit_transform(x))
scaled_x

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,1.097064,-2.073335,1.269934,0.984375,1.568466,3.283515,2.652874,2.532475,2.217515,2.255747,...,1.886690,-1.359293,2.303601,2.001237,1.307686,2.616665,2.109526,2.296076,2.750622,1.937015
1,1.829821,-0.353632,1.685955,1.908708,-0.826962,-0.487072,-0.023846,0.548144,0.001392,-0.868652,...,1.805927,-0.369203,1.535126,1.890489,-0.375612,-0.430444,-0.146749,1.087084,-0.243890,0.281190
2,1.579888,0.456187,1.566503,1.558884,0.942210,1.052926,1.363478,2.037231,0.939685,-0.398008,...,1.511870,-0.023974,1.347475,1.456285,0.527407,1.082932,0.854974,1.955000,1.152255,0.201391
3,-0.768909,0.253732,-0.592687,-0.764464,3.283553,3.402909,1.915897,1.451707,2.867383,4.910919,...,-0.281464,0.133984,-0.249939,-0.550021,3.394275,3.893397,1.989588,2.175786,6.046041,4.935010
4,1.750297,-1.151816,1.776573,1.826229,0.280372,0.539340,1.371011,1.428493,-0.009560,-0.562450,...,1.298575,-1.466770,1.338539,1.220724,0.220556,-0.313395,0.613179,0.729259,-0.868353,-0.397100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,2.110995,0.721473,2.060786,2.343856,1.041842,0.219060,1.947285,2.320965,-0.312589,-0.931027,...,1.901185,0.117700,1.752563,2.015301,0.378365,-0.273318,0.664512,1.629151,-1.360158,-0.709091
565,1.704854,2.085134,1.615931,1.723842,0.102458,-0.017833,0.693043,1.263669,-0.217664,-1.058611,...,1.536720,2.047399,1.421940,1.494959,-0.691230,-0.394820,0.236573,0.733827,-0.531855,-0.973978
566,0.702284,2.045574,0.672676,0.577953,-0.840484,-0.038680,0.046588,0.105777,-0.809117,-0.895587,...,0.561361,1.374854,0.579001,0.427906,-0.809587,0.350735,0.326767,0.414069,-1.104549,-0.318409
567,1.838341,2.336457,1.982524,1.735218,1.525767,3.272144,3.296944,2.658866,2.137194,1.043695,...,1.961239,2.237926,2.303601,1.653171,1.430427,3.904848,3.197605,2.289985,1.919083,2.219635
568,-1.808401,1.221792,-1.814389,-1.347789,-3.112085,-1.150752,-1.114873,-1.261820,-0.820070,-0.561032,...,-1.410893,0.764190,-1.432735,-1.075813,-1.859019,-1.207552,-1.305831,-1.745063,-0.048138,-0.751207

## 5.Model Building

In [10]:
x_train,x_test,y_train,y_test = train_test_split(scaled_x,y,test_size=0.20,shuffle=True,stratify=y)

In [11]:
x_train.shape,y_train.shape

((455, 30), (455,))

In [12]:
x_test.shape,y_test.shape

((114, 30), (114,))

In [29]:
gradient_boosting_clasifier = GradientBoostingClassifier(n_estimators=50,max_depth=3,learning_rate=0.3)

## 6.Model Training

In [30]:
start_time = datetime.now()
gradient_boosting_clasifier.fit(x_train,y_train)
end_time = datetime.now()

print("Time taken to Train the Algorthim:",end_time -start_time)

Time taken to Train the Algorthim: 0:00:00.513342

## 7.Model Testing || 8..Model Evaluation

### Training Data

In [26]:
y_pred_train = gdb_clasifier.predict(x_train)
print("Confusion_matricx\n" ,confusion_matrix(y_train,y_pred_train))
print("Accuracy_score"    ,accuracy_score(y_train,y_pred_train))
print("Precision_score"   ,precision_score(y_train,y_pred_train))
print("Recall_score"      ,recall_score(y_train,y_pred_train))

Confusion_matricx
 [[170   0]
 [  0 285]]
Accuracy_score 1.0
Precision_score 1.0
Recall_score 1.0

### Test Data

In [27]:
y_pred_test = gdb_clasifier.predict(x_test)
print("Confusion_matricx\n" ,confusion_matrix(y_test,y_pred_test))
print("Accuracy_score"    ,accuracy_score(y_test,y_pred_test))
print("Precision_score"   ,precision_score(y_test,y_pred_test))
print("Recall_score"      ,recall_score(y_test,y_pred_test))

Confusion_matricx
 [[39  3]
 [ 2 70]]
Accuracy_score 0.956140350877193
Precision_score 0.958904109589041
Recall_score 0.9722222222222222

## Extreme Gradient Boosting Machines?

In [28]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Downloading xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in d:\anaconda\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in d:\anaconda\lib\site-packages (from xgboost) (1.16.3)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/48.9 MB 1.1 MB/s eta 0:00:45
    --------------------------------------- 0.8/48.9 MB 1.1 MB/s eta 0:00:46
    --------------------------------------- 1.0/48.9 MB 1.2 MB/s eta 0:00:41
   - -------------------------------------- 1.3/48.9 MB 1.3 MB/s eta 0:00:37
   - -------------------------------------- 1.6/48.9 MB 1.3 MB/s eta 0:00:37
   - -------------------------------------- 2.4/48.9 MB 1.6 MB/s eta 0:00:30
   -- ------------------------------------- 2.9/48.9 MB 1.7 MB/s eta 0:00:27
   -- ------------------------------------- 3.7/48.9 MB 1.9 MB/s eta 0:00:24
   --- ------------------------------------ 4.5/48.9 MB 2.1 MB/s eta 0:00:21
   ---- ----------------------------------- 5.5/48.9 MB 2.4 MB/s eta 0:00:19
   ---- ----------------------------------- 6.0/48.9 MB 2.5 MB/s eta 0:00:18
   ----- ---------------------------------- 7.1/48.9 MB 2.6 MB/s eta 0:00:16
   ------ --------------------------------- 8.1/48.9 MB 2.8 MB/s eta 0:00:15
   ------- -------------------------------- 8.7/48.9 MB 2.8 MB/s eta 0:00:15
   -------- ------------------------------- 10.0/48.9 MB 3.0 MB/s eta 0:00:14
   -------- ------------------------------- 11.0/48.9 MB 3.1 MB/s eta 0:00:13
   --------- ------------------------------ 11.5/48.9 MB 3.1 MB/s eta 0:00:13
   ---------- ----------------------------- 12.6/48.9 MB 3.2 MB/s eta 0:00:12
   ----------- ---------------------------- 13.9/48.9 MB 3.3 MB/s eta 0:00:11
   ------------ --------------------------- 15.2/48.9 MB 3.5 MB/s eta 0:00:10
   ------------- -------------------------- 17.0/48.9 MB 3.7 MB/s eta 0:00:09
   --------------- ------------------------ 18.9/48.9 MB 3.9 MB/s eta 0:00:08
   --------------- ------------------------ 19.4/48.9 MB 3.9 MB/s eta 0:00:08
   ----------------- ---------------------- 21.0/48.9 MB 4.0 MB/s eta 0:00:07
   ------------------ --------------------- 22.3/48.9 MB 4.1 MB/s eta 0:00:07
   ------------------- -------------------- 23.6/48.9 MB 4.2 MB/s eta 0:00:07
   -------------------- ------------------- 25.4/48.9 MB 4.4 MB/s eta 0:00:06
   ---------------------- ----------------- 27.3/48.9 MB 4.5 MB/s eta 0:00:05
   ----------------------- ---------------- 29.1/48.9 MB 4.6 MB/s eta 0:00:05
   ------------------------- -------------- 31.2/48.9 MB 4.8 MB/s eta 0:00:04
   -------------------------- ------------- 32.8/48.9 MB 4.9 MB/s eta 0:00:04
   --------------------------- ------------ 33.8/48.9 MB 4.9 MB/s eta 0:00:04
   ---------------------------- ----------- 34.9/48.9 MB 4.9 MB/s eta 0:00:03
   ----------------------------- ---------- 35.7/48.9 MB 4.9 MB/s eta 0:00:03
   ------------------------------ --------- 37.0/48.9 MB 4.9 MB/s eta 0:00:03
   ------------------------------- -------- 38.5/48.9 MB 5.0 MB/s eta 0:00:03
   -------------------------------- ------- 39.8/48.9 MB 5.0 MB/s eta 0:00:02
   --------------------------------- ------ 41.2/48.9 MB 5.1 MB/s eta 0:00:02
   ----------------------------------- ---- 43.0/48.9 MB 5.1 MB/s eta 0:00:02
   ----------------------------------- ---- 44.0/48.9 MB 5.2 MB/s eta 0:00:01
   ------------------------------------ --- 45.1/48.9 MB 5.1 MB/s eta 0:00:01
   ------------------------------------- -- 45.9/48.9 MB 5.1 MB/s eta 0:00:01
   -------------------------------------- - 46.9/48.9 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------  48.0/48.9 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 5.1 MB/s eta 0:00:01
   ---------------------------------------- 48.9/48.9 MB 5.1 MB/s  0:00:09
Installing collected packages: xgboost
Successfully installed xgboost-3.4.1

In [31]:
import xgboost as xgb

In [51]:

start_time = datetime.now()
xgb_classifier = xgb.XGBClassifier(max_depth =3,n_estimators = 40,learning_rate = 0.0008,gamma = 1.9)
end_time = datetime.now()

print("Time taken to Train the Algorthim:",end_time -start_time)

Time taken to Train the Algorthim: 0:00:00.000496

## Training Data

In [50]:
start_time = datetime.now()
xgb_classifier.fit(x_train,y_train)
end_time = datetime.now()

print("Time taken to Train the Algorthim:",end_time -start_time)

Time taken to Train the Algorthim: 0:00:00.289924

## Testing Data|Evaluation

In [38]:
y_pred_train = xgb_classifier.predict(x_train)
print("Confusion Matrix:\n", confusion_matrix(y_train,y_pred_train))
print("Accuracy Score:"  ,accuracy_score(y_train,y_pred_train))
print("Precision Score:" ,precision_score(y_train,y_pred_train))
print("Recall Score:", recall_score(y_train,y_pred_train))

Confusion Matrix:
 [[  0 170]
 [  0 285]]
Accuracy Score: 0.6263736263736264
Precision Score: 0.6263736263736264
Recall Score: 1.0

In [40]:
y_pred_test = xgb_classifier.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_test))
print("Accuracy Score:"  ,accuracy_score(y_test,y_pred_test))
print("Precision Score:" ,precision_score(y_test,y_pred_test))
print("Recall Score:", recall_score(y_test,y_pred_test))

Confusion Matrix:
 [[ 0 42]
 [ 0 72]]
Accuracy Score: 0.631578947368421
Precision Score: 0.631578947368421
Recall Score: 1.0

In [41]:
from sklearn.metrics import classification_report

In [43]:
print(classification_report(y_test,y_pred_test))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        42
           1       0.63      1.00      0.77        72

    accuracy                           0.63       114
   macro avg       0.32      0.50      0.39       114
weighted avg       0.40      0.63      0.49       114

D:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
D:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
D:\anaconda\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

# THE END !!!