## 1.Import Necessary Libraties

In [14]:
import pandas as pd 

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.feature_selection import RFE

from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix

import warnings 
warnings.filterwarnings("ignore")

## 2.Import Dataset

In [2]:
credit_card_data = pd.read_csv("credit_card_clean.csv")
credit_card_data

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000.0,male,highschool,married,39,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,29997,150000.0,male,highschool,single,43,-1,-1,-1,-1,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,29998,30000.0,male,university,single,37,4,3,2,-1,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,29999,80000.0,male,highschool,married,41,1,-1,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,30000,50000.0,male,university,married,46,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

## 3.Data Undersatinding

In [3]:
credit_card_data.shape

(30000, 25)

In [4]:
credit_card_data.isna().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [5]:
credit_card_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX           object
EDUCATION     object
MARRIAGE      object
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

## 4.Data Preppuration

### 4.1 Remove Unwanted columns

In [6]:
credit_card_data.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [9]:
del credit_card_data["ID"]

In [10]:
credit_card_data.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,female,university,married,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,female,university,single,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,female,university,single,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,female,university,married,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,male,university,married,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [11]:
credit_card_data.shape

(30000, 24)

### ID is unwanted for the model prediction

### 4.2 change the Data type

In [16]:
le_model = LabelEncoder()
credit_card_data["SEX"] = le_model.fit_transform(credit_card_data["SEX"])
credit_card_data["EDUCATION"] = le_model.fit_transform(credit_card_data["EDUCATION"])
credit_card_data["MARRIAGE"] = le_model.fit_transform(credit_card_data["MARRIAGE"])
credit_card_data.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,0,3,0,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,0,3,2,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,0,3,2,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,0,3,0,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,1,3,0,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0

In [19]:
x = credit_card_data.drop(labels="DEFAULT",axis=1)
y = credit_card_data.DEFAULT

#### Change Input value scale

In [21]:
sd_scale = StandardScaler()
scaled_x = sd_scale.fit_transform(x)

## 5.Model Building

In [22]:
x_train,x_test,y_train,y_test = train_test_split(scaled_x,y,test_size=0.20,shuffle=True,stratify=y)

In [23]:
x_train.shape,y_train.shape

((24000, 23), (24000,))

In [24]:
x_test.shape,y_test.shape

((6000, 23), (6000,))

## 6.Model Training || 7.Model Testing || 8.Model Evaluation

In [28]:
def runrandomforestclassifier(x_train,x_test,y_train,y_test):
    rd_model = RandomForestClassifier(max_depth=10)
    rd_model.fit(x_train,y_train)

    y_pred_test = rd_model.predict(x_test)
    print("Accuracy_score  :",round(accuracy_score(y_test,y_pred_test),4))
    print("Precision_score :",round(precision_score(y_test,y_pred_test),4))
    print("Recall_score    :",round(recall_score(y_test,y_pred_test),4))
    print("Confusion_matrix:\n",confusion_matrix(y_test,y_pred_test))

### REF Feature selection

In [29]:
for i in range(1,25):
    ref_model = RFE(estimator = GradientBoostingClassifier(),n_features_to_select=i)
    ref_model.fit(x_train,y_train)

    x_train_ref_model = ref_model.transform(x_train)
    x_test_ref_model = ref_model.transform(x_test)

    print("Feature selection:",i)
    runrandomforestclassifier(x_train_ref_model,x_test_ref_model,y_train,y_test)
    print("**************************")

Feature selection: 1
Accuracy_score  : 0.8213
Precision_score : 0.7033
Recall_score    : 0.3323
Confusion_matrix:
 [[4487  186]
 [ 886  441]]
**************************
Feature selection: 2
Accuracy_score  : 0.8213
Precision_score : 0.7027
Recall_score    : 0.3331
Confusion_matrix:
 [[4486  187]
 [ 885  442]]
**************************
Feature selection: 3
Accuracy_score  : 0.8188
Precision_score : 0.684
Recall_score    : 0.3361
Confusion_matrix:
 [[4467  206]
 [ 881  446]]
**************************
Feature selection: 4
Accuracy_score  : 0.8188
Precision_score : 0.6695
Recall_score    : 0.3572
Confusion_matrix:
 [[4439  234]
 [ 853  474]]
**************************
Feature selection: 5
Accuracy_score  : 0.819
Precision_score : 0.6639
Recall_score    : 0.3677
Confusion_matrix:
 [[4426  247]
 [ 839  488]]
**************************
Feature selection: 6
Accuracy_score  : 0.8218
Precision_score : 0.6859
Recall_score    : 0.3587
Confusion_matrix:
 [[4455  218]
 [ 851  476]]
**************************
Feature selection: 7
Accuracy_score  : 0.8222
Precision_score : 0.6796
Recall_score    : 0.3708
Confusion_matrix:
 [[4441  232]
 [ 835  492]]
**************************
Feature selection: 8
Accuracy_score  : 0.8205
Precision_score : 0.6781
Recall_score    : 0.3587
Confusion_matrix:
 [[4447  226]
 [ 851  476]]
**************************
Feature selection: 9
Accuracy_score  : 0.8205
Precision_score : 0.6786
Recall_score    : 0.358
Confusion_matrix:
 [[4448  225]
 [ 852  475]]
**************************
Feature selection: 10
Accuracy_score  : 0.8213
Precision_score : 0.6798
Recall_score    : 0.3632
Confusion_matrix:
 [[4446  227]
 [ 845  482]]
**************************
Feature selection: 11
Accuracy_score  : 0.823
Precision_score : 0.6869
Recall_score    : 0.367
Confusion_matrix:
 [[4451  222]
 [ 840  487]]
**************************
Feature selection: 12
Accuracy_score  : 0.8215
Precision_score : 0.6818
Recall_score    : 0.3617
Confusion_matrix:
 [[4449  224]
 [ 847  480]]
**************************
Feature selection: 13
Accuracy_score  : 0.8223
Precision_score : 0.6867
Recall_score    : 0.3617
Confusion_matrix:
 [[4454  219]
 [ 847  480]]
**************************
Feature selection: 14
Accuracy_score  : 0.8223
Precision_score : 0.6856
Recall_score    : 0.3632
Confusion_matrix:
 [[4452  221]
 [ 845  482]]
**************************
Feature selection: 15
Accuracy_score  : 0.8207
Precision_score : 0.6806
Recall_score    : 0.3564
Confusion_matrix:
 [[4451  222]
 [ 854  473]]
**************************
Feature selection: 16
Accuracy_score  : 0.8223
Precision_score : 0.6867
Recall_score    : 0.3617
Confusion_matrix:
 [[4454  219]
 [ 847  480]]
**************************
Feature selection: 17
Accuracy_score  : 0.823
Precision_score : 0.6896
Recall_score    : 0.3632
Confusion_matrix:
 [[4456  217]
 [ 845  482]]
**************************
Feature selection: 18
Accuracy_score  : 0.8223
Precision_score : 0.6883
Recall_score    : 0.3595
Confusion_matrix:
 [[4457  216]
 [ 850  477]]
**************************
Feature selection: 19
Accuracy_score  : 0.8228
Precision_score : 0.688
Recall_score    : 0.364
Confusion_matrix:
 [[4454  219]
 [ 844  483]]
**************************
Feature selection: 20
Accuracy_score  : 0.8218
Precision_score : 0.6838
Recall_score    : 0.3617
Confusion_matrix:
 [[4451  222]
 [ 847  480]]
**************************
Feature selection: 21
Accuracy_score  : 0.8212
Precision_score : 0.6804
Recall_score    : 0.361
Confusion_matrix:
 [[4448  225]
 [ 848  479]]
**************************
Feature selection: 22
Accuracy_score  : 0.8228
Precision_score : 0.6924
Recall_score    : 0.358
Confusion_matrix:
 [[4462  211]
 [ 852  475]]
**************************
Feature selection: 23
Accuracy_score  : 0.8238
Precision_score : 0.6957
Recall_score    : 0.3617
Confusion_matrix:
 [[4463  210]
 [ 847  480]]
**************************
Feature selection: 24
Accuracy_score  : 0.8218
Precision_score : 0.6897
Recall_score    : 0.3534
Confusion_matrix:
 [[4462  211]
 [ 858  469]]
**************************

# THE END !!!